### ISSUE TITLE
Error when browsing a schema to populating a group (v 3.1.0)

### ISSUE THREAD

**Issue by tilkow** [dalibo/emaj_web#9]
Hello,

The following SQL error occurs:
`ERROR:  column "grpdef_log_schema_suffix" does not exist`

**Comment by tilkow** [comment]
[test-issue9.patch.zip](https://github.com/dalibo/emaj_web/files/3418358/test-issue9.patch.zip)

**Comment by beaud76** [comment]
Thanks a lot.
I have just pushed your fix proposal (commit eeee85f).
